[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#75715e"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f9f8f5"
yellow = "#f4bf75"

[colors.normal]
black = "#272822"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f8f8f2"
yellow = "#f4bf75"

[colors.primary]
background = "#171714"
foreground = "#f8f8f2"

[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Font Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 0.75

[window.dimensions]
columns = 80
lines = 25
